version: '3.8'

services:
  rdtm:
    build: .
    container_name: rdtm
    restart: unless-stopped
    
    environment:
      - RD_API_TOKEN=${RD_API_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MEDIA_PATH=${MEDIA_PATH:-/medias}
      - SCAN_INTERVAL_MINUTES=${SCAN_INTERVAL_MINUTES:-10}
    
    volumes:
      - rdtm_data:/app/data
      - rdtm_logs:/app/logs
      - ${MEDIA_PATH:-./medias}:/medias:ro
    
    ports:
      - "${PORT:-8000}:8000"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  rdtm_data:
  rdtm_logs: