name: Security Scan

on:
  schedule:
    - cron: '0 2 * * 1'  # Chaque lundi à 2h
  workflow_dispatch:

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Python dependency scan
      run: |
        pip install safety
        safety check --json --output safety-report.json || true
        
    - name: Node.js dependency scan
      run: |
        cd frontend
        npm audit --audit-level moderate --json > npm-audit.json || true
        
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          safety-report.json
          frontend/npm-audit.json

  container-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build image for scanning
      run: docker build -t rdtm:scan .
      
    - name: Scan container image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'rdtm:scan'
        format: 'json'
        output: 'container-scan.json'
        
    - name: Upload container scan results
      uses: actions/upload-artifact@v3
      with:
        name: container-scan
        path: container-scan.json
